@extends('layouts.admin')

@section('content')
<section class="admin-page admin-form-page admin-banner-form-page">
    <div class="admin-page-header"><div><a href="{{ route('admin.banners.index') }}" class="admin-back-link">← Quay lại danh sách banner</a><p class="admin-page-kicker">Melodify / Banner</p><h1 class="admin-page-title">Chỉnh sửa banner</h1><p class="admin-page-description">Cập nhật nội dung, liên kết, ảnh và vị trí hiển thị.</p></div></div>
    <form method="POST" action="{{ route('admin.banners.update', $item->getKey()) }}" enctype="multipart/form-data" class="ant-card admin-resource-form admin-banner-form" autocomplete="off">
        @csrf @method('PUT')
        <div class="admin-resource-form-heading"><div><strong>Thông tin banner</strong><span>Các trường có dấu * là bắt buộc. Tên tối đa 160 ký tự.</span></div><span class="ant-tag ant-tag-blue">Đang chỉnh sửa</span></div>
        <div class="admin-banner-form-layout">
            <div class="admin-banner-form-fields">
                <div class="admin-form-group"><label class="admin-form-label" for="banner-title">Tên banner <span>*</span></label><input id="banner-title" name="title" data-slug-source="banner-slug" value="{{ old('title', $item->title) }}" maxlength="160" class="ant-input admin-form-input @error('title') is-invalid @enderror" required>@error('title')<p class="admin-field-error">{{ $message }}</p>@enderror</div>
                <div class="admin-form-group"><label class="admin-form-label" for="banner-slug">Slug</label><div class="admin-slug-input-row"><input id="banner-slug" name="slug" value="{{ old('slug', $item->slug) }}" maxlength="180" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" class="ant-input admin-form-input @error('slug') is-invalid @enderror" placeholder="tu-dong-theo-ten"><button type="button" class="ant-btn admin-slug-reset" data-slug-reset="banner-slug">Theo tên</button></div><p class="admin-field-help">Tự tạo theo tên, hoặc tự sửa; slug không được trùng.</p>@error('slug')<p class="admin-field-error">{{ $message }}</p>@enderror</div>
                <div class="admin-form-group admin-form-span"><label class="admin-form-label" for="banner-link-url">URL khi nhấn vào banner</label><input id="banner-link-url" name="link_url" type="text" value="{{ old('link_url', $item->link_url) }}" maxlength="500" class="ant-input admin-form-input @error('link_url') is-invalid @enderror" placeholder="/home hoặc https://melodify.vn/..."><p class="admin-field-help">Chỉ dùng đường dẫn nội bộ bắt đầu bằng / hoặc URL http(s) hợp lệ.</p>@error('link_url')<p class="admin-field-error">{{ $message }}</p>@enderror</div>
                <div class="admin-form-group"><label class="admin-form-label" for="banner-sort-order">Thứ tự hiển thị <span>*</span></label><input id="banner-sort-order" name="sort_order" type="number" min="0" max="999999" step="1" inputmode="numeric" value="{{ old('sort_order', $item->sort_order) }}" class="ant-input admin-form-input @error('sort_order') is-invalid @enderror" required><p class="admin-field-help">Số nhỏ hơn sẽ được hiển thị trước.</p>@error('sort_order')<p class="admin-field-error">{{ $message }}</p>@enderror</div>
                <div class="admin-form-group"><label class="admin-form-label" for="banner-status">Trạng thái <span>*</span></label><select id="banner-status" name="status" class="ant-input admin-form-input @error('status') is-invalid @enderror" required><option value="active" @selected(old('status', $item->status) === 'active')>Đang hiển thị</option><option value="inactive" @selected(old('status', $item->status) === 'inactive')>Tạm ẩn</option></select>@error('status')<p class="admin-field-error">{{ $message }}</p>@enderror</div>
            </div>
            <aside class="admin-banner-upload-card"><div class="admin-banner-preview" data-banner-preview>@if(filled($item->image_url))<img src="{{ $item->image_url }}" alt="Ảnh banner hiện tại">@else<x-anticon name="cloud-upload" aria-hidden="true" /><strong>Chưa có ảnh</strong><span>Ảnh sẽ được lưu trong Cloudinary / banner</span>@endif</div><label class="admin-form-label" for="banner-image">Ảnh banner</label><input id="banner-image" name="image" type="file" accept="image/jpeg,image/png,image/webp" class="ant-input admin-form-input @error('image') is-invalid @enderror" data-banner-input><p class="admin-field-help">JPG, PNG hoặc WebP, tối đa 5 MB. Bỏ trống để giữ ảnh hiện tại.</p>@error('image')<p class="admin-field-error">{{ $message }}</p>@enderror</aside>
        </div>
        <div class="admin-form-actions admin-resource-form-actions"><a href="{{ route('admin.banners.index') }}" class="ant-btn">Hủy</a><button type="submit" class="ant-btn ant-btn-primary">Lưu thay đổi</button></div>
    </form>
</section>
@endsection
