@php($selectedArtistIds = collect(old('artist_ids', $item?->artist_ids ?? []))->map(fn ($id) => (string) $id)->all())
@php($selectedGenreIds = collect(old('genre_ids', $item?->genre_ids ?? []))->map(fn ($id) => (string) $id)->all())
@php($selectedTopicIds = collect(old('topic_ids', $item?->topic_ids ?? []))->map(fn ($id) => (string) $id)->all())
@php($selectedPlaylistIds = collect(old('playlist_ids', $item?->playlist_ids ?? []))->map(fn ($id) => (string) $id)->all())
<div class="admin-banner-section-heading admin-form-span">
    <span class="admin-banner-section-marker" aria-hidden="true"></span>
    <div><strong>Nội dung liên quan</strong><p>Có thể chọn nhiều mục để frontend biết banner đang giới thiệu nội dung nào.</p></div>
</div>
<div class="admin-form-group"><label class="admin-form-label">Nghệ sĩ liên quan</label><div class="admin-selection-panel admin-selection-panel-compact" data-selection-panel><input type="search" class="ant-input admin-selection-search" placeholder="Tìm nghệ sĩ..." data-selection-search><div class="admin-selection-list">@forelse($artists ?? [] as $artist)<label class="admin-selection-option" data-selection-option><input type="checkbox" name="artist_ids[]" value="{{ $artist->getKey() }}" @checked(in_array((string) $artist->getKey(), $selectedArtistIds, true))><span><strong>{{ $artist->name }}</strong><small>{{ $artist->slug }}</small></span></label>@empty<div class="admin-selection-empty">Chưa có nghệ sĩ.</div>@endforelse</div></div>@error('artist_ids')<p class="admin-field-error">{{ $message }}</p>@enderror</div>
<div class="admin-form-group"><label class="admin-form-label">Thể loại liên quan</label><div class="admin-selection-panel admin-selection-panel-compact" data-selection-panel><input type="search" class="ant-input admin-selection-search" placeholder="Tìm thể loại..." data-selection-search><div class="admin-selection-list">@forelse($genres ?? [] as $genre)<label class="admin-selection-option" data-selection-option><input type="checkbox" name="genre_ids[]" value="{{ $genre->getKey() }}" @checked(in_array((string) $genre->getKey(), $selectedGenreIds, true))><span><strong>{{ $genre->name }}</strong><small>{{ $genre->slug }}</small></span></label>@empty<div class="admin-selection-empty">Chưa có thể loại.</div>@endforelse</div></div>@error('genre_ids')<p class="admin-field-error">{{ $message }}</p>@enderror</div>
<div class="admin-form-group"><label class="admin-form-label">Chủ đề liên quan</label><div class="admin-selection-panel admin-selection-panel-compact" data-selection-panel><input type="search" class="ant-input admin-selection-search" placeholder="Tìm chủ đề..." data-selection-search><div class="admin-selection-list">@forelse($topics ?? [] as $topic)<label class="admin-selection-option" data-selection-option><input type="checkbox" name="topic_ids[]" value="{{ $topic->getKey() }}" @checked(in_array((string) $topic->getKey(), $selectedTopicIds, true))><span><strong>{{ $topic->name }}</strong><small>{{ $topic->slug }}</small></span></label>@empty<div class="admin-selection-empty">Chưa có chủ đề.</div>@endforelse</div></div>@error('topic_ids')<p class="admin-field-error">{{ $message }}</p>@enderror</div>
<div class="admin-form-group"><label class="admin-form-label">Playlist liên quan</label><div class="admin-selection-panel admin-selection-panel-compact" data-selection-panel><input type="search" class="ant-input admin-selection-search" placeholder="Tìm playlist..." data-selection-search><div class="admin-selection-list">@forelse($playlists ?? [] as $playlist)<label class="admin-selection-option" data-selection-option><input type="checkbox" name="playlist_ids[]" value="{{ $playlist->getKey() }}" @checked(in_array((string) $playlist->getKey(), $selectedPlaylistIds, true))><span><strong>{{ $playlist->name }}</strong><small>{{ $playlist->type_custom ?: $playlist->type }}</small></span></label>@empty<div class="admin-selection-empty">Chưa có playlist.</div>@endforelse</div></div>@error('playlist_ids')<p class="admin-field-error">{{ $message }}</p>@enderror</div>
